Added more commonly used basic commands.
CodeMaxx/Terminal-Commands-Beginner pull request #19
Opened 2018-02-16 22:16 UTC by ankurparihar

Added pushd, popd, dirs, gzip, zip, unzip etc. commands

2018-02-16 22:17 UTC, ankurparihar commented
Improvements.

2018-02-17 08:32 UTC, CodeMaxx requested changes

2018-02-17 08:32 UTC, CodeMaxx commented on README.md
> +`gzip -d <file_to_decompress>` - used to extract the .gz file<br>
Please add `gunzip <file_to_decompress>.gz` as well since it's very similar to this command

2018-02-17 08:32 UTC, CodeMaxx commented on README.md
> +`gzip file1 file2 file3` - used to compress any number of files into a .gz compressed format.<br>
Mention that this method compresses each of the files separately and not into a single .gz archive.

2018-02-17 08:34 UTC, CodeMaxx commented
I've added a couple of comments. The rests looks good. Thanks for using proper format for the Readme!

2018-02-18 05:59 UTC, ankurparihar commented
Changes done.

2018-02-18 08:24 UTC, closed without merging